### ISSUE TITLE
webpack unable to parse wasm_game_of_life_bg.wasm file

### ISSUE THREAD

**Issue by bantic** [rustwasm/rustwasm.github.io#39]
I ran through the initial steps of the tutorial, and when attempting to run `npm run start`, the `@webassemblyjs` npm module (used by webpack) fails to parse the wasm file and reports this error:

```
ERROR in ../pkg/wasm_game_of_life_bg.wasm
Module parse failed: Unexpected section: 0x86
You may need an appropriate loader to handle this file type.
Error: Unexpected section: 0x86
    at new CompileError (/Users/coryforsyth/work/recurse/wasm-game-of-life/www/node_modules/@webassemblyjs/helper-api-error/lib/index.js:40:109)
```

Full stacktrace:

<details>

```
➜  www git:(master) npm run start

> create-wasm-app@0.1.0 start /Users/coryforsyth/work/recurse/wasm-game-of-life/www
> webpack-dev-server

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
Failed to decode custom "name" section @1670; ignoring (integer representation too long).
✖ ｢wdm｣: Hash: ba812e844349a72f78d6
Version: webpack 4.29.3
Time: 355ms
Built at: 02/14/2019 4:32:22 PM
         Asset       Size  Chunks             Chunk Names
0.bootstrap.js   3.15 KiB       0  [emitted]
  bootstrap.js    354 KiB    main  [emitted]  main
    index.html  175 bytes          [emitted]
Entrypoint main = bootstrap.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 ./bootstrap.js 40 bytes {main} [built]
[../pkg/wasm_game_of_life.js] 708 bytes {0} [built]
[./bootstrap.js] 279 bytes {main} [built]
[./index.js] 58 bytes {0} [built]
[./node_modules/ansi-html/index.js] 4.16 KiB {main} [built]
[./node_modules/events/events.js] 13.3 KiB {main} [built]
[./node_modules/html-entities/index.js] 231 bytes {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/url/url.js] 22.8 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 7.78 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} [built]
    + 14 hidden modules

ERROR in ../pkg/wasm_game_of_life_bg.wasm
Module parse failed: Unexpected section: 0x86
You may need an appropriate loader to handle this file type.
Error: Unexpected section: 0x86
    at new CompileError (/Users/coryforsyth/work/recurse/wasm-game-of-life/www/node_modules/@webassemblyjs/helper-api-error/lib/index.js:40:109)
    at parseSection (/Users/coryforsyth/work/recurse/wasm-game-of-life/www/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1542:11)
    at Object.decode (/Users/coryforsyth/work/recurse/wasm-game-of-life/www/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1559:25)
    at decode (/Users/coryforsyth/work/recurse/wasm-game-of-life/www/node_modules/@webassemblyjs/wasm-parser/lib/index.js:240:21)
    at WebAssemblyParser.parse (/Users/coryforsyth/work/recurse/wasm-game-of-life/www/node_modules/webpack/lib/wasm/WebAssemblyParser.js:74:19)
    at doBuild.err (/Users/coryforsyth/work/recurse/wasm-game-of-life/www/node_modules/webpack/lib/NormalModule.js:460:32)
    at runLoaders (/Users/coryforsyth/work/recurse/wasm-game-of-life/www/node_modules/webpack/lib/NormalModule.js:342:12)
    at /Users/coryforsyth/work/recurse/wasm-game-of-life/www/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/coryforsyth/work/recurse/wasm-game-of-life/www/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/coryforsyth/work/recurse/wasm-game-of-life/www/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/coryforsyth/work/recurse/wasm-game-of-life/www/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/coryforsyth/work/recurse/wasm-game-of-life/www/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/coryforsyth/work/recurse/wasm-game-of-life/www/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
 @ ../pkg/wasm_game_of_life.js 2:0-47 8:71-82 9:45-56 26:11-21
 @ ./index.js
 @ ./bootstrap.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./bootstrap.js

ERROR in chunk 0
6c4dfe4822eee2ca2a6d.module.wasm
/Users/coryforsyth/work/recurse/wasm-game-of-life/pkg/wasm_game_of_life_bg.wasm
unexpected end
ℹ ｢wdm｣: Failed to compile.
```

</details>

I've run through this tutorial in the past without issue (~ 3 weeks ago), so this seems like it may be due to a change in the cargo dependencies in that time. I went to my old code (that worked without issue) and, after issuing a `cargo update` there, I see the same issue reported here.

I'm using macOS High Sierra (10.13.6), `rustc 1.34.0-nightly (d8a0dd7ae 2019-01-28)` and `rustup 1.16.0 (beab5ac2b 2018-12-06)`. A copy of my `Cargo.lock` is at [this gist](https://gist.github.com/86b56cbc54fb2f420fad069b37fbcda9).

**Comment by fitzgen** [comment]
Thanks for filing an issue!

This is a latent bug in a library that webpack uses, which was recently triggered by updates in `wasm-bindgen`. Follow https://github.com/webpack/webpack/pull/8786 for the fix to enter webpack.

In the meantime, you can try hardcoding `wasm-bindgen = "=0.2.34"` in your `Cargo.toml`.

**Comment by bantic** [comment]
That did the trick, thank you!
